[workspace]
members = [
    "crates/ast",
    "crates/bir",
    "crates/sema",
    "crates/cst",
    "crates/lir",
    "crates/tyc",
    "crates/tyls",
    "crates/utils",
]

[profile.release]
debug = true
