[package]
name = "tylang"
version = "0.1.0"
authors = ["Tyler Lanphear <animemachine13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "~0.8.2"
clap = "~2.33.0"
