[package]
name = "sema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bir = { path = "../bir/" }
bimap = "0.4.0"
assert_matches = "1.5.0"
